In [8]:
from components.controllers import SSLController

In [9]:
c = SSLController(1,2)


In [10]:
import numpy as np

In [11]:
c.M @ np.array([[1,2,3,4]]).T

array([[1.41421356],
       [0.        ],
       [1.25      ]])

In [12]:
c.transform_velocities(np.array([[1,2,3,4]]).T)


array([[1.41421356],
       [0.        ],
       [1.25      ]])

In [13]:
a,b,t = c.transform_velocities(np.array([[1,2,3,4]]).T)


In [14]:
a,b,t

(array([1.41421356]), array([0.]), array([1.25]))

In [15]:
v = np.array([0,2]).T 
np.hstack((v, [0]))

array([0, 2, 0])

In [16]:
v

array([0, 2])

In [17]:
from numpy.linalg import norm

In [18]:
norm(v)

2.0

In [19]:
from decision_making.decision import ConstantDecision
ws = np.array(np.array([[1,3,1,-1]])).T
d = ConstantDecision(ws)

In [54]:
from components.robot import SSLRobot

r = SSLRobot(d, [350,10], 1, 1)

In [55]:
r.update()

In [56]:
c.M


array([[-0.35355339, -0.35355339,  0.35355339,  0.35355339],
       [ 0.35355339, -0.35355339, -0.35355339,  0.35355339],
       [ 0.125     ,  0.125     ,  0.125     ,  0.125     ]])

In [57]:
Mi = np.linalg.pinv(c.M)

In [58]:
v = c.M @ r.ws 

In [59]:
v

array([[-1.06066017],
       [-1.06066017],
       [ 0.375     ]])

In [68]:
iws =  Mi @ v

In [69]:
iws

array([[ 0.75],
       [ 2.25],
       [ 0.75],
       [-0.75]])

In [70]:
r.ws 

array([[ 1],
       [ 2],
       [ 1],
       [-1]])

In [71]:
c.M @ iws

array([[-1.06066017],
       [-1.06066017],
       [ 0.375     ]])

In [72]:
psi = 0.5
R = np.array([
        [np.cos(psi), -np.sin(psi), 0],
        [np.sin(psi), np.cos(psi), 0],
        [0, 0, 1]
    ])

In [73]:
R

array([[ 0.87758256, -0.47942554,  0.        ],
       [ 0.47942554,  0.87758256,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [75]:
np.linalg.inv(R)

array([[ 0.87758256,  0.47942554,  0.        ],
       [-0.47942554,  0.87758256,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])