In [1]:
from components.controllers import SSLController

In [2]:
c = SSLController(1,2)


In [3]:
import numpy as np

In [4]:
c.M @ np.array([[1,2,3,4]]).T

array([[1.41421356],
       [0.        ],
       [1.25      ]])

In [5]:
c.transform_velocities(np.array([[1,2,3,4]]).T)


array([[1.41421356],
       [0.        ],
       [1.25      ]])

In [6]:
a,b,t = c.transform_velocities(np.array([[1,2,3,4]]).T)


In [7]:
a,b,t

(array([1.41421356]), array([0.]), array([1.25]))

In [8]:
v = np.array([0,2]).T 
np.hstack((v, [0]))

array([0, 2, 0])

In [9]:
v

array([0, 2])

In [10]:
from numpy.linalg import norm

In [11]:
norm(v)

2.0

In [58]:
from decision_making.decision import ConstantDecision
ws = np.array([[0.01,0,-0.01,0]]).T
d = ConstantDecision(ws)

In [59]:
type(d)

decision_making.decision.ConstantDecision

In [60]:
from components.robot import SSLRobot

r = SSLRobot(d, [0,0], 1, 1)

In [63]:
r.v

array([[-0.00707107],
       [ 0.00707107],
       [ 0.        ]])

In [57]:
r.v

array([[0.],
       [0.],
       [0.]])

In [30]:
ref_v[2:]

np.concatenate((lin_v, ref_v[2:]))


array([[0. ],
       [0. ],
       [0.5]])

In [21]:
r.update()

array([[1],
       [0],
       [1],
       [0]])

In [38]:
def constrain_angle(angle):
    return (angle + np.pi) % (2 * np.pi) - np.pi

In [48]:
[v v]



[array([[1.41421356],
        [0.        ],
        [1.25      ]]),
 array([[1.41421356],
        [0.        ],
        [1.25      ]])]

In [46]:
constrain_angle(-3*np.pi/2)





1.5707963267948966

In [37]:
np.unwrap([3*np.pi])


array([9.42477796])

In [24]:
r.v

array([0, 0, 0])

In [25]:
v = c.transform_velocities(np.array([[1,2,3,4]]).T)

In [12]:
v.shape == (3,1)

True

In [15]:
v

array([[1.41421356],
       [0.        ],
       [1.25      ]])

In [18]:
v[:2] + v[:2]

array([[2.82842712],
       [0.        ]])

In [20]:
v[0]*= -1

In [21]:
v[0]

array([-1.41421356])

In [24]:
from constants.field_constants import *


In [31]:
p =np.array([BALL_START_POS]).T

In [34]:
p[1]

array([300])